### ISSUE TITLE
Minor version release request

### ISSUE THREAD

**Issue by trecenti** [redbooth/percona_migrator#32]
Hi folks,

I've been planning to add PerconaMigrator gem to our project and we noticed that the latest released gem v0.1.0.rc.6 does not have stdout logging implemented, I've though noticed that it was recently merged into master, here's a comparison since last release:
https://github.com/redbooth/percona_migrator/compare/v0.1.0.rc.6...master

I was wondering if we could bump a minor version and release so we could benefit from the logging.

@sauloperez if we can make this release, it wouldn't need to add a general logging for whether PerconaMigrator is being used, making #31 not needed.

**Comment by sauloperez** [comment]
Sure we will. I'm afraid though that that's not enough as `pt-online-schema-change`, the underlying binary that gets executed, outputs in a streaming fashion. So to show its output as it happens, we'll need read by lines and log them as they become available.

I'll investigate it today and I let you know.

**Comment by trecenti** [comment]
I've done some testing with master and it is outputting `pt-online-schema-change` stdout when I run `db:migrate` which is what we're looking for.

**Comment by sauloperez** [comment]
Then, if it's enough for you we can release a new version. I'll get to it later.

**Comment by trecenti** [comment]
> I'll get to it later.

Thanks, let me know if you need me to do anything, and feel free to close this when you're done.

**Comment by sauloperez** [comment]
Done! I just released version 0.1.0.rc.7 👌

**Comment by trecenti** [comment]
> Done! I just released version 0.1.0.rc.7 👌

Thanks @sauloperez

**Comment by sauloperez** [comment]
FYI @trecenti https://github.com/redbooth/percona_migrator/pull/33
