### ISSUE TITLE
creating v4.2 branch

### ISSUE THREAD

**Issue by aserafin** [redbooth/percona_migrator#38]
Thanks for releasing this gem!

I added support for rails 4.2.x in this [fork](https://github.com/redbooth/percona_migrator/compare/master...aserafin:v4.2?expand=1)

Could you create v4.2 branch so I can make pull request and get your opinions?

**Comment by franciscoj** [comment]
Hi! You can just open the pull request against master. We'll have a look and review it ASAP.

Thanks a lot!!

**Comment by aserafin** [comment]
Created pr #39 - looking forward to your feedback :)

**Comment by sauloperez** [comment]
Closing then
