### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by mguterl** [redbooth/percona_migrator#41]
I'm interested in working on Rails 5 support for percona_migrator. Do you have any preferences on methods for supporting multiple versions of Rails?

I have seen gems designate certain version numbers for certain versions of Rails. For example percona_migrator 1.x.x series is for Rails 4.x and percona_migrator 2.x.x is for Rails 5.x, etc.

I have also seen gems that detect which version of Rails is running and monkeypatch Rails with the correct strategy/adapter.

Is there anything to that I should be aware of before trying to start this work?

**Comment by sauloperez** [comment]
Hi @mguterl , thanks a lot for answering so fast to our call!

First of all I need to mention that the repo and the gem will have to be renamed not to be confused with a Percona product. I will update the README file for everyone to know and publish a blog post about it. 

That being said, regarding the versioning, our idea is to follow semver and so we'll bump up each major version of the gem with every major version of Rails, just as you suggested. I'm not fully aware of the changes that ActiveRecord 4.2 brings compared to 4.1, but I assume they don't require a major version.

As for the things that you should know before starting, first, note that we group the code related with the AR adapter in `lib/active_record` as in Rails and the code that connects to `pt-online-schema-change` in `lib/percona_migrator`. The `lib/lhm` folder contains the adapter that converts LHM's to Rails' DSL, which I believe you won't need to touch.

Something that might be a bit counter intuitive at first is the fact that `Command` is the class responsible of executing the `pt-online-schema-change` in a child process, while `Runner` receives the final SQL statement from rails and passes it to a `Command` instance. That's something I plan to tweak a bit to make it more understandable.

Also, you will need to start a `v5.0` branch from master.

Apart from that, https://github.com/redbooth/percona_migrator#how-it-works and https://github.com/redbooth/percona_migrator#development sections should be enough.

Let me know if you need help on something. I'll update these sections with whatever comes up.

Thanks again!

**Comment by wyhaines** [comment]
Has there been any additional progress on making Departure work with Rails 5?

**Comment by sauloperez** [comment]
Nothing so far. Feel free to take it.

**Comment by sauloperez** [comment]
@wyhaines any news? Did you give it a try?

**Comment by wyhaines** [comment]
I did.  I have a PR that passes all specs and appears to work. The actual body of work is fairly small, once it was all said and done.

https://github.com/redbooth/departure/pull/81

**Comment by sauloperez** [comment]
Rails v5.1 support it's implemented but we're still missing v5.0.

**Comment by wyhaines** [comment]
There should be very little difference between what I did for 5.1 and what is needed for 5.0.

**Comment by sauloperez** [comment]
moved to https://github.com/departurerb/departure/issues/9
