### ISSUE TITLE
cannot find DBI on Mac

### ISSUE THREAD

**Issue by gammons** [redbooth/percona_migrator#42]
Hi there, 

This tool looks fantastic and it's exactly what my team is looking for.  I'm having a bit of trouble getting it to work locally on my machine, however.  I installed `percona-toolkit` via homebrew, but when I actually run a migration it's giving me the following error:

```
PerconaMigrator::Error: Cannot connect to MySQL: Cannot connect to MySQL because the Perl DBI module is not installed or not found.  Run 'perl -MDBI' to see the directories that Perl searches for DBI.  If DBI is not installed, try:
  Debian/Ubuntu  apt-get install libdbi-perl
  RHEL/CentOS    yum install perl-DBI
  OpenSolaris    pkg install pkg:/SUNWpmdbi
```

What should I hunt down to install to fix this issue?  I did try installing `libdbi` via homebrew, but that did not have an effect. 

Thanks!

**Comment by sauloperez** [comment]
Hi! happy to see that it fits your needs!

Yep, I managed to reproduce it with a fresh `brew install percona-toolkit`. It must be something with the brew formula. I'll take a look.

**Comment by sauloperez** [comment]
Can you please try running the `pt-online-schema-change` command that gets printed when the migration starts?

You should see an output like:

```shell
==  AddRowOrderToTaskLists: migrating =========================================
-- change_table(:task_lists, {:bulk=>true})

   -> Running pt-online-schema-change --execute --statistics --recursion-method=none --alter-foreign-keys-method=auto -h localhost -u root D=teambox_development,t=task_lists --alter "ADD \`row_order\` MEDIUMINT(11) NOT NULL DEFAULT 0"

(...)
```

Does it work when ran manually?

It does work for me, so it's very likely that some alias, path, etc. set by homebrew it's not present when ran through a child process. That would explain why when running from a shell, the perl DBI module is found.

**Comment by gammons** [comment]
Running `pt-online-shema-change` without the gem yielded the same error.  So I ran `cpan` and `install DBI`, but now running `pt-online-schema-change` segfaults.  Sooooo, yeah.  This is obviously not an issue with the gem but something crazy with my system.  Thanks for taking a look!

**Comment by sauloperez** [comment]
Ok. Let us know if you find something worth sharing

**Comment by liujunao** [comment]
Running `pt-archiver` show `segmentation fault:11` error after I install DBI and DBD::mysql by cpan.If I uninstall DBI and DBD::mysql,then showing `Cannot connect to MySQL` error
