### ISSUE TITLE
Rename of Percona Migrator

### ISSUE THREAD

**Issue by sauloperez** [redbooth/percona_migrator#43]
Hi everyone! this week Percona reach us out to ask us to change the name of the gem so that it doesn't cause confusion on who is the actual author.

We open the question to everyone to suggest a new name for percona migrator. We've been thinking about removing `migrator` and use a single word. The ideas we have are: `departure`, `exile` or `immigrane`. Because `exile` has a bit negative connotation and there is already a gem called `immigrant`, `departure` seems to be our favorite.

thoughts?

**Comment by enricostano** [comment]
Why not just `gem install migraine`?

Ouch! https://rubygems.org/gems/migraine

**Comment by sauloperez** [comment]
Yes! We are late. There are lots of awesome names taken!

**Comment by web64** [comment]
How about a twist on Departure: DBarture :)

**Comment by sauloperez** [comment]
lol that's interesting!

**Comment by andresgutgon** [comment]
What about `pergola_migrator`? it remains close to original name. I know some guy that have a lot of expertise on pergolas :trollface:

**Comment by sauloperez** [comment]
Thanks for helping, guys. Finally we have decided to go with `departure`.
