### ISSUE TITLE
Options overriding schema proposal

### ISSUE THREAD

**Issue by aserafin** [redbooth/percona_migrator#50]
Hey, 

Currently you are blocking usage of `PERCONA_ARGS` env variable when executing `rake db:migrate` [here](https://github.com/redbooth/departure/blob/fd7cb91ccd122593e2dbd99424907d7e0153f609/lib/percona_migrator.rb#L42) but we are actually running this command and  would like to set `—recursion-method none` for all migrations. I was thinking about it and come up with 2 solutions:

1. To allow using it
2. To introduce new config variable in `PerconaMigrator::Configuration`, for example `global_cmd_options` that would have the same syntax as `PERCONA_AGRS`, leverage `UserOptions` class to parse it and change `CliGenerator#all_options` to sth like this:

````
def all_options
  env_options = UserOptions.new
  global_cmd_options = UserOptions.new(PerconaMigrator.configuration.global_cmd_options)
  options = DEFAULT_OPTIONS.merge(global_cmd_options).merge(env_options).to_a
  options.join(' ')
end
````

so we would have options overriding schema: default < global < env

Let me know what do you think and I'm happy to work on pull request implementing this :)

**Comment by sauloperez** [comment]
The 2nd option seems quite good and the way to go. Happy to see the work on `UserOptions` paid off :).

Let me know if you need some help, although I'll be off until next Tuesday.

**Comment by sauloperez** [comment]
Resolved by https://github.com/redbooth/departure/pull/52
