### ISSUE TITLE
Filtering out mysql password from logs

### ISSUE THREAD

**Issue by aserafin** [redbooth/percona_migrator#51]
Hey, 

We noticed that currently mysql password is placed in logs when executing percona. I took a look at the code and also see 2 options to fix it:

1. filter out with regexp `command_line.gsub(/-p .*? -/, '-p [filtered]')` [here](https://github.com/redbooth/departure/blob/master/lib/percona_migrator/command.rb#L88) - this won't be ideal as regexp is not the best tool to do this and it might break in case we change argument order etc.

2. Do refactor and make `PerconaMigrator::Command` accept `cli_generator` and `sql` instead of already generated string. That way we could add `sanitize` parameter to `CliGenerator#generate` and `CliGenerator#parse_statement` and push it down to `ConnectionDetails` object so we can do proper replacement in `password_argument` method

I would actually prefer 2nd option as it's more bulletproof, but wan to check with you before sending PR

**Comment by sauloperez** [comment]
I go with the 2nd option as well. Looking forward for your PR!

**Comment by aserafin** [comment]
Fixed with #53 - thanks @sauloperez 👍
