### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by sauloperez** [redbooth/percona_migrator#73]
So far we only have a little section in the README.md but without any instructions on how to proceed with a code change. This would help onboarding new contributors (hopefully).

Now github adds links to that file when opening a new PR.

**Comment by sauloperez** [comment]
## Some examples of contribution guidelines

Spree has a [small contributing section](https://github.com/spree/spree#contributing) not only about code contributions and also a [CONTRIBUTING.md](https://github.com/spree/spree/blob/master/.github/CONTRIBUTING.md).

On the other hand, Rubocop has only a [CONTRIBUTING.md](https://github.com/bbatsov/rubocop/blob/master/CONTRIBUTING.md).

Any other good examples of contribution guidelines @enricostano @franciscoj @aserafin ?

**Comment by franciscoj** [comment]
don't overthink it :grimacing: small contribution section is enough. When we need more, we can add more.

**Comment by sauloperez** [comment]
my point is that https://github.com/redbooth/departure#contributing might not be enough. I don't see streams of contributors :trollface:

**Comment by enricostano** [comment]
I would go with all the contributing content in `CONTRIBUTING.md` and a link to it in `README.md`

**Comment by franciscoj** [comment]
Let's not worry about this until we have docens of contributros and that becomes a problem. Add anote on the README and that's it. Don't overengineer this.

**Comment by sauloperez** [comment]
Moved to https://github.com/departurerb/departure/issues/3
