### ISSUE TITLE
It's not possible to specify load options

### ISSUE THREAD

**Issue by benlangfeld** [redbooth/percona_migrator#78]
[`--max-load`](https://www.percona.com/doc/percona-toolkit/2.2/pt-online-schema-change.html#cmdoption-pt-online-schema-change--max-load) and [`--critical-load`](https://www.percona.com/doc/percona-toolkit/2.2/pt-online-schema-change.html#cmdoption-pt-online-schema-change--critical-load) both accept an array of MySQL status variables as arguments, e.g.,

    --critical-load Threads_running=500,Threads_created=1000

Unfortunately, departure currently doesn't [parse this argument format correctly](https://github.com/redbooth/departure/blob/v4.0.0/lib/departure/option.rb#L6).

**Comment by neildecapia** [comment]
Addressed in https://github.com/redbooth/departure/pull/76.

**Comment by benlangfeld** [comment]
Thanks @neildecapia , I hadn't spotted that!
