### ISSUE TITLE
Move repo to its own organization

### ISSUE THREAD

**Issue by sauloperez** [redbooth/percona_migrator#82]
With the latest changes in Redbooth we should move the repo away from Redbooth's GitHub organization. I suggest we create a `departure` organization and we move it to it.

**Comment by andresgutgon** [comment]
`departure` from Redbooth :trollface:

**Comment by sauloperez** [comment]
what a troll :trollface:

**Comment by sauloperez** [comment]
Done in https://github.com/departurerb/departure. I'll move all issues there now.
