### ISSUE TITLE
pt-osc - output maxing at 8 chars

### ISSUE THREAD

**Issue by garettarrowood** [redbooth/percona_migrator#84]
Running migrations locally, I do not encounter this problem.  However, when my demo and production servers run migrations during deployment (on VM running Linux, with migration triggered by Capistrano), the logs are always messed up.  Here is a gist of one such migration - 

https://gist.github.com/garettarrowood/42449b48709d85017a13bd5e522183ab

I think the issue is the `read_nonblock(8)` method here - https://github.com/redbooth/departure/blob/master/lib/departure/command.rb#L47 .

I'll open a PR, tie my repo to it, and see if just raising the number to 40 solves the problem.  But before I do, can you provide some reference why a max length of 8 is used here? What problem might I create by changing it?

---

Upon further thought - it seems more likely `logger.write_no_newline(data)` is not working correctly.

**Comment by sauloperez** [comment]
moved to https://github.com/departurerb/departure/issues/2
